
services:
  bionix-pipeline:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        NIX_VERSION: 2.13.3
    image: bionix-pipeline:0.1.0
    volumes:
      - .:/app
      - nix-store:/nix
    working_dir: /app
    command: tail -f /dev/null  # This will keep the container running
    tty: true
    stdin_open: true

volumes:
  nix-store:    
