name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3


    - name: Build and run tests
      run: |
        docker compose build
        docker compose up -d
        docker compose exec -T bionix-pipeline /bin/sh -c "
          chmod +x /usr/local/bin/enter-nix-shell &&
          /usr/local/bin/enter-nix-shell -c '
            echo \"Running tests...\" &&
            figlet \"bionix-pipeline\" | lolcat &&
            echo \"Add your test commands here\"
          '
        "

    - name: Cleanup
      run: docker compose down
